plugins { id 'com.android.application' }

android {
    namespace 'ir.khanehremap.diag'
    compileSdk 35

    defaultConfig {
        applicationId 'ir.khanehremap.smartdiag'
        minSdk 24
        targetSdk 34
        versionCode 29004
        versionName '2.9.4'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

configurations.configureEach {
    resolutionStrategy {
        force 'androidx.browser:browser:1.8.0'
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.6.2'
    implementation 'androidx.browser:browser:1.8.0'
}
