plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.careai.guardian'
    compileSdk 35

    signingConfigs {
        stable {
            storeFile file('../signing/careai-update.jks')
            storePassword 'CareAI2026Key'
            keyAlias 'careai'
            keyPassword 'CareAI2026Key'
        }
    }

    defaultConfig {
        applicationId "ir.careai.guardian"
        minSdk 26
        targetSdk 35
        versionCode 9
        versionName "9.0-PRO-UPDATE"
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stable
        }
        release {
            signingConfig signingConfigs.stable
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.mediapipe:tasks-vision:1.0.0'
}
