plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.careai.guardian'
    compileSdk 35

    defaultConfig {
        applicationId "ir.careai.guardian"
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName "5.0-CARE-ASSIST"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.mediapipe:tasks-vision:1.0.0'
}
