plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.careai.guardian'
    compileSdk 35

    defaultConfig {
        applicationId "ir.careai.guardian"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0-M1"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
